services:
  postgres:
    platform: linux/amd64
    image: postgres:15-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-notificator}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-notificator123}
      POSTGRES_DB: ${DB_DATABASE:-notificator}
    volumes:
      - postgres_data_v15:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-notificator}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    platform: linux/amd64
    image: redis:7-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}

  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:3.13-management-alpine
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-notificator}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq123}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    restart: unless-stopped

  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - '${WAHA_PORT:-3000}:3000/tcp'
    environment:
      WHATSAPP_HOOK_URL: ${WHATSAPP_HOOK_URL:-http://notificator:8080/api/webhooks/whatsapp}
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_RESTART_ALL_SESSIONS: "true"
    volumes:
      - waha_data:/app/.sessions
    networks:
      - backend
    restart: unless-stopped

  notificator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8081}:8080'
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_DATABASE:-notificator}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-notificator}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-notificator123}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-notificator}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-rabbitmq123}
      WAHA_BASE_URL: http://waha:3000
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      waha:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres_data_v15:
  redis_data:
  rabbitmq_data:
  waha_data: